MacAddresses:
  - name: "NAS"
    address: "00:11:22:00:00:00"
    Host: "192.168.60.1"
  - name: "Home Server"
    address: "00:11:22:00:00:01"
    Host: "192.168.60.2"
  - name: "File Server"
    address: "00:11:22:00:00:02"
    Host: "192.168.60.3"
  - name: "Media Center PC"
    address: "00:11:22:00:00:03"
