MacAddresses:
  - name: "NAS"
    address: "00:11:22:00:00:00"
  - name: "Home Server"
    address: "00:11:22:00:00:01"
  - name: "File Server"
    address: "00:11:22:00:00:02"
  - name: "Media Center PC"
    address: "00:11:22:00:00:03"
