name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.23
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        make all

    - run: |
        set -x
        assets=()
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" build/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/ajnasz/wolweb:${{ github.ref_name }} .

    # Push the Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/ajnasz/wolweb:${{ github.ref_name }}
